name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths: [ "api/koa" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/koa  
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.GCP_DOCKER_REGISTRY}}:$(date +%s)
